"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from comfydeploy.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .createrunresponse import CreateRunResponse, CreateRunResponseTypedDict
    from .deploymentrunrequest import (
        DeploymentRunRequest,
        DeploymentRunRequestTypedDict,
        Gpu,
        Inputs,
        InputsTypedDict,
    )
    from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
    from .mediaitem import MediaItem, MediaItemTypedDict
    from .security import Security, SecurityTypedDict
    from .validationerror import (
        Loc,
        LocTypedDict,
        ValidationError,
        ValidationErrorTypedDict,
    )
    from .workflowrunmodel import WorkflowRunModel, WorkflowRunModelTypedDict
    from .workflowrunoutputmodel import (
        Data,
        DataTypedDict,
        WorkflowRunOutputModel,
        WorkflowRunOutputModelTypedDict,
    )

__all__ = [
    "CreateRunResponse",
    "CreateRunResponseTypedDict",
    "Data",
    "DataTypedDict",
    "DeploymentRunRequest",
    "DeploymentRunRequestTypedDict",
    "Gpu",
    "HTTPMetadata",
    "HTTPMetadataTypedDict",
    "Inputs",
    "InputsTypedDict",
    "Loc",
    "LocTypedDict",
    "MediaItem",
    "MediaItemTypedDict",
    "Security",
    "SecurityTypedDict",
    "ValidationError",
    "ValidationErrorTypedDict",
    "WorkflowRunModel",
    "WorkflowRunModelTypedDict",
    "WorkflowRunOutputModel",
    "WorkflowRunOutputModelTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "CreateRunResponse": ".createrunresponse",
    "CreateRunResponseTypedDict": ".createrunresponse",
    "DeploymentRunRequest": ".deploymentrunrequest",
    "DeploymentRunRequestTypedDict": ".deploymentrunrequest",
    "Gpu": ".deploymentrunrequest",
    "Inputs": ".deploymentrunrequest",
    "InputsTypedDict": ".deploymentrunrequest",
    "HTTPMetadata": ".httpmetadata",
    "HTTPMetadataTypedDict": ".httpmetadata",
    "MediaItem": ".mediaitem",
    "MediaItemTypedDict": ".mediaitem",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "Loc": ".validationerror",
    "LocTypedDict": ".validationerror",
    "ValidationError": ".validationerror",
    "ValidationErrorTypedDict": ".validationerror",
    "WorkflowRunModel": ".workflowrunmodel",
    "WorkflowRunModelTypedDict": ".workflowrunmodel",
    "Data": ".workflowrunoutputmodel",
    "DataTypedDict": ".workflowrunoutputmodel",
    "WorkflowRunOutputModel": ".workflowrunoutputmodel",
    "WorkflowRunOutputModelTypedDict": ".workflowrunoutputmodel",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
