"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from comfydeploy.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from enum import Enum
from pydantic import model_serializer
from typing import Any, Dict, List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


InputsTypedDict = TypeAliasType(
    "InputsTypedDict", Union[str, int, float, bool, List[Any]]
)


Inputs = TypeAliasType("Inputs", Union[str, int, float, bool, List[Any]])


class Gpu(str, Enum):
    r"""The GPU to override the machine's default GPU"""

    CPU = "CPU"
    T4 = "T4"
    L4 = "L4"
    A10_G = "A10G"
    L40_S = "L40S"
    A100 = "A100"
    A100_80_GB = "A100-80GB"
    H100 = "H100"
    H200 = "H200"
    B200 = "B200"


class DeploymentRunRequestTypedDict(TypedDict):
    deployment_id: str
    inputs: NotRequired[Dict[str, InputsTypedDict]]
    r"""The inputs to the workflow"""
    webhook: NotRequired[str]
    webhook_intermediate_status: NotRequired[bool]
    gpu: NotRequired[Gpu]
    r"""The GPU to override the machine's default GPU"""
    flags: NotRequired[Nullable[List[str]]]
    r"""Array of flag strings"""


class DeploymentRunRequest(BaseModel):
    deployment_id: str

    inputs: Optional[Dict[str, Inputs]] = None
    r"""The inputs to the workflow"""

    webhook: Optional[str] = None

    webhook_intermediate_status: Optional[bool] = False

    gpu: Optional[Gpu] = None
    r"""The GPU to override the machine's default GPU"""

    flags: OptionalNullable[List[str]] = UNSET
    r"""Array of flag strings"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["inputs", "webhook", "webhook_intermediate_status", "gpu", "flags"]
        )
        nullable_fields = set(["flags"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
