"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from comfydeploy.types import BaseModel
from typing_extensions import TypedDict


class DeploymentCreateTypedDict(TypedDict):
    workflow_version_id: str
    workflow_id: str
    machine_id: str
    environment: str


class DeploymentCreate(BaseModel):
    workflow_version_id: str

    workflow_id: str

    machine_id: str

    environment: str
