"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .eventupdate import EventUpdate, EventUpdateTypedDict
from comfydeploy.types import BaseModel
from comfydeploy.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, TypedDict


class EventUpdateEventTypedDict(TypedDict):
    data: EventUpdateTypedDict
    event: Literal["event_update"]


class EventUpdateEvent(BaseModel):
    data: EventUpdate

    EVENT: Annotated[
        Annotated[
            Optional[Literal["event_update"]],
            AfterValidator(validate_const("event_update")),
        ],
        pydantic.Field(alias="event"),
    ] = "event_update"
