"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from comfydeploy.types import BaseModel
from typing_extensions import TypedDict


class FileUploadResponseTypedDict(TypedDict):
    message: str
    r"""A message indicating the result of the file upload"""
    file_id: str
    r"""The unique identifier for the uploaded file"""
    file_name: str
    r"""The original name of the uploaded file"""
    file_url: str
    r"""The URL where the uploaded file can be accessed"""


class FileUploadResponse(BaseModel):
    message: str
    r"""A message indicating the result of the file upload"""

    file_id: str
    r"""The unique identifier for the uploaded file"""

    file_name: str
    r"""The original name of the uploaded file"""

    file_url: str
    r"""The URL where the uploaded file can be accessed"""
