"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from comfydeploy.types import BaseModel
from datetime import datetime
from typing_extensions import TypedDict


class LogDataContentTypedDict(TypedDict):
    logs: str
    timestamp: datetime
    r"""Timestamp in UTC"""


class LogDataContent(BaseModel):
    logs: str

    timestamp: datetime
    r"""Timestamp in UTC"""
