"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .logdatacontent import LogDataContent, LogDataContentTypedDict
from comfydeploy.types import BaseModel
from enum import Enum
import pydantic
from typing import Final, Optional, TypedDict
from typing_extensions import Annotated


class Event(str, Enum):
    LOG_UPDATE = "log_update"

class LogUpdateEventTypedDict(TypedDict):
    data: LogDataContentTypedDict
    

class LogUpdateEvent(BaseModel):
    data: LogDataContent
    EVENT: Annotated[Final[Optional[Event]], pydantic.Field(alias="event")] = Event.LOG_UPDATE # type: ignore
    
