"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from comfydeploy.types import BaseModel
from typing_extensions import TypedDict


class OutputModelTypedDict(TypedDict):
    class_type: str
    output_id: str


class OutputModel(BaseModel):
    class_type: str

    output_id: str
