"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from comfydeploy.types import BaseModel
from typing_extensions import TypedDict


class WorkflowWithNameTypedDict(TypedDict):
    id: str
    name: str


class WorkflowWithName(BaseModel):
    id: str

    name: str
