"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from comfydeploy.models.components import (
    httpmetadata as components_httpmetadata,
    runstream as components_runstream,
)
from comfydeploy.types import BaseModel
from comfydeploy.utils import eventstreaming
import pydantic
from pydantic import SkipValidation
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateRunWorkflowStreamRunWorkflowStreamPostResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    run_stream: NotRequired[
        Union[
            eventstreaming.EventStream[components_runstream.RunStreamTypedDict],
            eventstreaming.EventStreamAsync[components_runstream.RunStreamTypedDict],
        ]
    ]
    r"""Stream of workflow run events"""


class CreateRunWorkflowStreamRunWorkflowStreamPostResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    run_stream: SkipValidation[
        Optional[
            Union[
                eventstreaming.EventStream[components_runstream.RunStream],
                eventstreaming.EventStreamAsync[components_runstream.RunStream],
            ]
        ]
    ] = None
    r"""Stream of workflow run events"""
