"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from comfydeploy.models.components import (
    createrunresponse as components_createrunresponse,
    deploymentrunrequest as components_deploymentrunrequest,
    httpmetadata as components_httpmetadata,
    modelrunrequest as components_modelrunrequest,
    workflowrunrequest as components_workflowrunrequest,
    workflowrunversionrequest as components_workflowrunversionrequest,
)
from comfydeploy.types import BaseModel
import pydantic
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


CreateRunQueueRunQueuePostDataTypedDict = TypeAliasType(
    "CreateRunQueueRunQueuePostDataTypedDict",
    Union[
        components_deploymentrunrequest.DeploymentRunRequestTypedDict,
        components_modelrunrequest.ModelRunRequestTypedDict,
        components_workflowrunversionrequest.WorkflowRunVersionRequestTypedDict,
        components_workflowrunrequest.WorkflowRunRequestTypedDict,
    ],
)


CreateRunQueueRunQueuePostData = TypeAliasType(
    "CreateRunQueueRunQueuePostData",
    Union[
        components_deploymentrunrequest.DeploymentRunRequest,
        components_modelrunrequest.ModelRunRequest,
        components_workflowrunversionrequest.WorkflowRunVersionRequest,
        components_workflowrunrequest.WorkflowRunRequest,
    ],
)


class CreateRunQueueRunQueuePostResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    create_run_response: NotRequired[
        components_createrunresponse.CreateRunResponseTypedDict
    ]
    r"""Successful Response"""


class CreateRunQueueRunQueuePostResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    create_run_response: Optional[components_createrunresponse.CreateRunResponse] = None
    r"""Successful Response"""
