"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from comfydeploy.models.components import (
    assetresponse as components_assetresponse,
    httpmetadata as components_httpmetadata,
)
from comfydeploy.types import BaseModel
from comfydeploy.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetAssetAssetsAssetIDGetRequestTypedDict(TypedDict):
    asset_id: str


class GetAssetAssetsAssetIDGetRequest(BaseModel):
    asset_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class GetAssetAssetsAssetIDGetResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    asset_response: NotRequired[components_assetresponse.AssetResponseTypedDict]
    r"""Successful Response"""


class GetAssetAssetsAssetIDGetResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    asset_response: Optional[components_assetresponse.AssetResponse] = None
    r"""Successful Response"""
