"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from comfydeploy import utils
from dataclasses_json import Undefined, dataclass_json
from typing import Optional


@dataclasses.dataclass
class GetWebsocketDeploymentIDRequest:
    deployment_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'deployment_id', 'style': 'simple', 'explode': False }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class GetWebsocketDeploymentIDResponseBody:
    r"""Workflow queued"""
    ws_connection_url: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('ws_connection_url') }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class GetWebsocketDeploymentIDResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field(metadata={'dataclasses_json': { 'exclude': lambda f: True }})
    object: Optional[GetWebsocketDeploymentIDResponseBody] = dataclasses.field(default=None)
    r"""Workflow queued"""
    

