"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from comfydeploy import utils
from dataclasses_json import Undefined, dataclass_json
from typing import List, Optional


@dataclasses.dataclass
class GetDeploymentIDInputsRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ResponseBody:
    class_type: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('class_type') }})
    input_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('input_id') }})
    default_value: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('default_value') }})
    min_value: float = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('min_value') }})
    max_value: float = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('max_value') }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class GetDeploymentIDInputsResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field(metadata={'dataclasses_json': { 'exclude': lambda f: True }})
    response_bodies: Optional[List[ResponseBody]] = dataclasses.field(default=None)
    r"""Retrieve the output"""
    

