"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from comfydeploy.models.components import httpmetadata as components_httpmetadata
from comfydeploy.types import BaseModel
from comfydeploy.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class GetWebsocketDeploymentIDRequestTypedDict(TypedDict):
    deployment_id: str
    

class GetWebsocketDeploymentIDRequest(BaseModel):
    deployment_id: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    

class GetWebsocketDeploymentIDResponseBodyTypedDict(TypedDict):
    r"""Workflow queued"""
    
    ws_connection_url: str
    

class GetWebsocketDeploymentIDResponseBody(BaseModel):
    r"""Workflow queued"""
    
    ws_connection_url: str
    

class GetWebsocketDeploymentIDResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    object: NotRequired[GetWebsocketDeploymentIDResponseBodyTypedDict]
    r"""Workflow queued"""
    

class GetWebsocketDeploymentIDResponse(BaseModel):
    http_meta: Annotated[Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)] = None
    object: Optional[GetWebsocketDeploymentIDResponseBody] = None
    r"""Workflow queued"""
    
