"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from comfydeploy.models.components import httpmetadata as components_httpmetadata
from comfydeploy.types import BaseModel, Nullable, UNSET_SENTINEL
from comfydeploy.utils import FieldMetadata, PathParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class GetWorkflowVersionVersionIDRequestTypedDict(TypedDict):
    version_id: str
    

class GetWorkflowVersionVersionIDRequest(BaseModel):
    version_id: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    

class WorkflowTypedDict(TypedDict):
    pass
    

class Workflow(BaseModel):
    pass
    

class GetWorkflowVersionVersionIDWorkflowAPITypedDict(TypedDict):
    pass
    

class GetWorkflowVersionVersionIDWorkflowAPI(BaseModel):
    pass
    

class GetWorkflowVersionVersionIDSnapshotTypedDict(TypedDict):
    pass
    

class GetWorkflowVersionVersionIDSnapshot(BaseModel):
    pass
    

class GetWorkflowVersionVersionIDDependenciesTypedDict(TypedDict):
    pass
    

class GetWorkflowVersionVersionIDDependencies(BaseModel):
    pass
    

class GetWorkflowVersionVersionIDResponseBodyTypedDict(TypedDict):
    r"""Retrieve the output"""
    
    workflow_id: str
    id: str
    workflow: WorkflowTypedDict
    workflow_api: GetWorkflowVersionVersionIDWorkflowAPITypedDict
    user_id: Nullable[str]
    comment: Nullable[str]
    version: float
    snapshot: GetWorkflowVersionVersionIDSnapshotTypedDict
    dependencies: GetWorkflowVersionVersionIDDependenciesTypedDict
    created_at: str
    updated_at: str
    

class GetWorkflowVersionVersionIDResponseBody(BaseModel):
    r"""Retrieve the output"""
    
    workflow_id: str
    id: str
    workflow: Workflow
    workflow_api: GetWorkflowVersionVersionIDWorkflowAPI
    user_id: Nullable[str]
    comment: Nullable[str]
    version: float
    snapshot: GetWorkflowVersionVersionIDSnapshot
    dependencies: GetWorkflowVersionVersionIDDependencies
    created_at: str
    updated_at: str
    
    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = []
        nullable_fields = ["user_id", "comment"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields
                or (
                    k in optional_fields
                    and k in nullable_fields
                    and (
                        self.__pydantic_fields_set__.intersection({n})
                        or k in null_default_fields
                    )  # pylint: disable=no-member
                )
            ):
                m[k] = val

        return m
        

class GetWorkflowVersionVersionIDResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    object: NotRequired[GetWorkflowVersionVersionIDResponseBodyTypedDict]
    r"""Retrieve the output"""
    

class GetWorkflowVersionVersionIDResponse(BaseModel):
    http_meta: Annotated[Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)] = None
    object: Optional[GetWorkflowVersionVersionIDResponseBody] = None
    r"""Retrieve the output"""
    
