"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from comfydeploy.models.components import httpmetadata as components_httpmetadata
from comfydeploy.types import BaseModel
from comfydeploy.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class GetV1MachinesMachineIDRequestTypedDict(TypedDict):
    machine_id: str
    ext_urls: NotRequired[str]
    

class GetV1MachinesMachineIDRequest(BaseModel):
    machine_id: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    ext_urls: Annotated[Optional[str], pydantic.Field(alias="extUrls"), FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = "false"
    

class GetV1MachinesMachineIDResponseBodyTypedDict(TypedDict):
    r"""Specific machine retrieved successfully"""
    
    id: NotRequired[str]
    name: NotRequired[str]
    type: NotRequired[str]
    status: NotRequired[str]
    created_at: NotRequired[str]
    updated_at: NotRequired[str]
    message: NotRequired[str]
    

class GetV1MachinesMachineIDResponseBody(BaseModel):
    r"""Specific machine retrieved successfully"""
    
    id: Optional[str] = None
    name: Optional[str] = None
    type: Optional[str] = None
    status: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    message: Optional[str] = None
    

class GetV1MachinesMachineIDResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    object: NotRequired[GetV1MachinesMachineIDResponseBodyTypedDict]
    r"""Specific machine retrieved successfully"""
    

class GetV1MachinesMachineIDResponse(BaseModel):
    http_meta: Annotated[Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)] = None
    object: Optional[GetV1MachinesMachineIDResponseBody] = None
    r"""Specific machine retrieved successfully"""
    
