"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import List, Optional


class Environment(str, Enum):
    PRODUCTION = 'production'
    STAGING = 'staging'


@dataclasses.dataclass
class GetDeploymentRequest:
    environment: Optional[Environment] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'environment', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class GetDeploymentResponseBody:
    pass


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class GetDeploymentResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field(metadata={'dataclasses_json': { 'exclude': lambda f: True }})
    response_bodies: Optional[List[GetDeploymentResponseBody]] = dataclasses.field(default=None)
    r"""Display all production workflows"""
    

