"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from comfydeploy.models.components import httpmetadata as components_httpmetadata
from comfydeploy.types import BaseModel
import pydantic
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class PostMachineEndpointRequestBodyTypedDict(TypedDict):
    machine_id: str
    type: str
    

class PostMachineEndpointRequestBody(BaseModel):
    machine_id: str
    type: str
    

class PostMachineEndpointResponseBodyTypedDict(TypedDict):
    r"""Create short lived machine endpoint"""
    
    url: str
    gpu: str
    

class PostMachineEndpointResponseBody(BaseModel):
    r"""Create short lived machine endpoint"""
    
    url: str
    gpu: str
    

class PostMachineEndpointResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    object: NotRequired[PostMachineEndpointResponseBodyTypedDict]
    r"""Create short lived machine endpoint"""
    

class PostMachineEndpointResponse(BaseModel):
    http_meta: Annotated[Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)] = None
    object: Optional[PostMachineEndpointResponseBody] = None
    r"""Create short lived machine endpoint"""
    
