"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from comfydeploy.models.components import (
    httpmetadata as components_httpmetadata,
    modelwithmetadata as components_modelwithmetadata,
)
from comfydeploy.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PublicModelsModelsGetResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    response_public_models_models_get: NotRequired[
        List[components_modelwithmetadata.ModelWithMetadataTypedDict]
    ]
    r"""Successful Response"""


class PublicModelsModelsGetResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    response_public_models_models_get: Optional[
        List[components_modelwithmetadata.ModelWithMetadata]
    ] = None
    r"""Successful Response"""
