"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from comfydeploy.models.components import (
    httpmetadata as components_httpmetadata,
    searchmodelsresponse as components_searchmodelsresponse,
)
from comfydeploy.types import BaseModel
from comfydeploy.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SearchSearchModelGetRequestTypedDict(TypedDict):
    query: str
    provider: NotRequired[str]


class SearchSearchModelGetRequest(BaseModel):
    query: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]

    provider: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "all"


class SearchSearchModelGetResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    search_models_response: NotRequired[
        components_searchmodelsresponse.SearchModelsResponseTypedDict
    ]
    r"""Successful Response"""


class SearchSearchModelGetResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    search_models_response: Optional[
        components_searchmodelsresponse.SearchModelsResponse
    ] = None
    r"""Successful Response"""
