"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from comfydeploy.models.components import (
    fileuploadresponse as components_fileuploadresponse,
    httpmetadata as components_httpmetadata,
)
from comfydeploy.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UploadFileFileUploadPostResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    file_upload_response: NotRequired[
        components_fileuploadresponse.FileUploadResponseTypedDict
    ]
    r"""Successful Response"""


class UploadFileFileUploadPostResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    file_upload_response: Optional[components_fileuploadresponse.FileUploadResponse] = (
        None
    )
    r"""Successful Response"""
