"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "comfydeploy"
__version__: str = "0.7.0"
__openapi_doc_version__: str = "V2"
__gen_version__: str = "2.560.1"
__user_agent__: str = "speakeasy-sdk/python 0.7.0 2.560.1 V2 comfydeploy"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
